Import('qt_env')

env = qt_env.Clone()

env.AddExtraMoc(env.Glob('*.h'))

env.AppendUnique(CPPDEFINES = [ 'BSAEXTRACTOR_LIBRARY' ])

env.RequireLibraries('bsatk')

env.AppendUnique(CPPPATH = [
    '${BOOSTPATH}'
])

env.AppendUnique(LIBPATH = "${ZLIBPATH}/build")
env.AppendUnique(LIBS = 'zlibstatic')

lib = env.SharedLibrary('bsaExtractor', env.Glob('*.cpp'))
env.InstallModule(lib)

res = env['QT_USED_MODULES']
Return('res')
